mod commands;
pub mod db;
mod models;
use log::info;
use tauri::Manager;
use tauri_specta::{collect_commands, Builder};

fn setup_logging(app_handle: &tauri::AppHandle) {
    let log_path = app_handle
        .path()
        .app_data_dir()
        .expect("failed to get app data dir")
        .join("chant.log");

    if let Some(parent) = log_path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }

    let _ = fern::Dispatch::new()
        .format(|out, message, record| {
            out.finish(format_args!(
                "[{}][{}][{}] {}",
                chrono::Local::now().format("%Y-%m-%d %H:%M:%S"),
                record.level(),
                record.target(),
                message
            ))
        })
        .level(log::LevelFilter::Info)
        .level_for("sqlx", log::LevelFilter::Warn)
        .chain(std::io::stdout())
        .chain(fern::log_file(&log_path).expect("Failed to open log file"))
        .apply();

    info!("Logging initialized → {:?}", log_path);
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::list_collections,
        commands::add_collection,
        commands::delete_collection,
        commands::clear_all_data,
        commands::get_library_stats,
        commands::get_database_path,
        // Settings
        commands::get_setting,
        commands::set_setting,
        commands::get_all_settings,
        // Debug
        commands::debug_query_table,
        // Tracks
        commands::list_tracks,
        commands::get_track,
        commands::update_track,
        // Artists
        commands::list_artists,
        commands::list_artist_rows,
        // Albums
        commands::list_albums,
        commands::list_album_rows,
        commands::list_tracks_by_album,
        commands::scan_collection,
        commands::get_cover_art,
        commands::get_album_cover_art,
        commands::get_artist_cover_art,
    ]);

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// This file is auto-generated by Specta. Do not edit.\n// @ts-nocheck\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_opener::init())
        .setup(|app| {
            let handle = app.handle().clone();

            // Initialize logging first
            setup_logging(&handle);

            // Initialize database
            tauri::async_runtime::block_on(async move {
                match db::init_db(&handle).await {
                    Ok(pool) => {
                        info!("Database initialized successfully");
                        handle.manage(pool);
                    }
                    Err(e) => {
                        log::error!("Failed to initialize database: {}", e);
                        panic!("Database initialization failed: {}", e);
                    }
                }
            });
            Ok(())
        })
        .invoke_handler(builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
