// This file is auto-generated by Specta. Do not edit.
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listCollections() : Promise<Result<Collection[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_collections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addCollection(input: CollectionInput) : Promise<Result<Collection, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_collection", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCollection(collectionId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_collection", { collectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAllData() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLibraryStats() : Promise<Result<LibraryStats, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_library_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDatabasePath() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_database_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSetting(key: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllSettings() : Promise<Result<Setting[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async debugQueryTable(tableName: string) : Promise<Result<(Partial<{ [key in string]: string }>)[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_query_table", { tableName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTracks() : Promise<Result<TrackRow[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tracks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTrack(trackId: number) : Promise<Result<TrackRow, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_track", { trackId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTrack(trackId: number, input: TrackUpdateInput) : Promise<Result<TrackRow, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_track", { trackId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listArtists() : Promise<Result<Artist[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_artists") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listArtistRows() : Promise<Result<ArtistRow[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_artist_rows") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAlbums(artistId: number | null) : Promise<Result<Album[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_albums", { artistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAlbumRows() : Promise<Result<AlbumRow[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_album_rows") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTracksByAlbum(albumId: number) : Promise<Result<TrackRow[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tracks_by_album", { albumId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanCollection(collectionId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_collection", { collectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCoverArt(trackId: number) : Promise<Result<CoverArt | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cover_art", { trackId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAlbumCoverArt(albumId: number) : Promise<Result<CoverArt | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_album_cover_art", { albumId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getArtistCoverArt(artistId: number) : Promise<Result<CoverArt | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artist_cover_art", { artistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Album = { id: number; title: string; artistId: number | null; year: number | null; genre: string | null; coverPath: string | null; musicbrainzId: string | null; createdAt: string }
export type AlbumRow = { id: number; title: string; artistName: string | null; year: number | null; genre: string | null; trackCount: number; totalDurationSecs: number; totalSizeBytes: number }
export type AppError = { Database: string } | { NotFound: string } | { InvalidInput: string } | { Io: string } | { Serialization: string }
export type Artist = { id: number; name: string; sortName: string | null; musicbrainzId: string | null; createdAt: string }
export type ArtistRow = { id: number; name: string; sortName: string | null; albumCount: number; trackCount: number; totalDurationSecs: number }
export type Collection = { id: number; path: string; label: string | null; createdAt: string }
export type CollectionInput = { path: string; label: string | null }
export type CoverArt = { 
/**
 * Base64-encoded image data
 */
data: string; 
/**
 * MIME type, e.g. "image/jpeg" or "image/png"
 */
mimeType: string }
export type LibraryStats = { totalCollections: number; totalArtists: number; totalAlbums: number; totalTracks: number; totalSizeBytes: number; totalDurationSecs: number }
export type Setting = { key: string; value: string }
export type TrackRow = { id: number; collectionId: number; albumId: number | null; artistId: number | null; title: string; trackNumber: number | null; discNumber: number | null; durationSecs: number | null; filePath: string; fileSizeBytes: number; fileFormat: string | null; bitrateKbps: number | null; sampleRateHz: number | null; lyrics: string | null; createdAt: string; updatedAt: string; artistName: string | null; albumTitle: string | null; albumCoverPath: string | null }
export type TrackUpdateInput = { title: string | null; trackNumber: number | null; discNumber: number | null; lyrics: string | null; 
/**
 * Set to Some("") to clear, Some("Name") to find-or-create, None to keep existing
 */
artistName: string | null; 
/**
 * Set to Some("") to clear, Some("Title") to find-or-create, None to keep existing
 */
albumTitle: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
