/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableRouteImport } from './routes/table'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists_.$artistId'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums_.$albumId'

const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/artists_/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/albums_/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRoute
  '/debug': typeof DebugRoute
  '/settings': typeof SettingsRoute
  '/table': typeof TableRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRoute
  '/debug': typeof DebugRoute
  '/settings': typeof SettingsRoute
  '/table': typeof TableRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRoute
  '/debug': typeof DebugRoute
  '/settings': typeof SettingsRoute
  '/table': typeof TableRoute
  '/albums_/$albumId': typeof AlbumsAlbumIdRoute
  '/artists_/$artistId': typeof ArtistsArtistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/artists'
    | '/debug'
    | '/settings'
    | '/table'
    | '/albums/$albumId'
    | '/artists/$artistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums'
    | '/artists'
    | '/debug'
    | '/settings'
    | '/table'
    | '/albums/$albumId'
    | '/artists/$artistId'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/artists'
    | '/debug'
    | '/settings'
    | '/table'
    | '/albums_/$albumId'
    | '/artists_/$artistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRoute
  ArtistsRoute: typeof ArtistsRoute
  DebugRoute: typeof DebugRoute
  SettingsRoute: typeof SettingsRoute
  TableRoute: typeof TableRoute
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists_/$artistId': {
      id: '/artists_/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums_/$albumId': {
      id: '/albums_/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRoute,
  ArtistsRoute: ArtistsRoute,
  DebugRoute: DebugRoute,
  SettingsRoute: SettingsRoute,
  TableRoute: TableRoute,
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
